name: dartregistry
version: 1.3.1
author: Roberto Tassi <roberto.tassi@fromlabs.org>
description: A simple dependency injection library
homepage: https://github.com/fromlabs/dartregistry
environment:
  sdk: ">=1.12.0 <2.0.0"
dependencies:
  logging: ^0.11.0
  reflectable: ^1.0.0
transformers:
- reflectable:
    entry_points:
      - test/registry_test.dart