name: dartregistry
version: 1.2.5
author: Roberto Tassi <roberto.tassi@fromlabs.org>
description: A sample command-line application
homepage: https://github.com/fromlabs/dartregistry
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  logging: ">=0.11.0 <0.12.0"
  stack_trace: ">=1.4.0 <2.0.0"