name: dartregistry
version: 1.2.8
author: Roberto Tassi <roberto.tassi@fromlabs.org>
description: A sample command-line application
homepage: https://github.com/fromlabs/dartregistry
environment:
  sdk: ">=1.12.0 <2.0.0"
dependencies:
  logging: ^0.11.0
  stack_trace: ^1.5.0